import os  # For accessing environment variables
import json
from dotenv import load_dotenv  # For loading .env files
import sys
import pathlib # Import pathlib

# Determine the base directory of the application (project root)
# This assumes config.py is in the root or a subdirectory of the project.
# If config.py is in the root, BASE_DIR will be the project root.
# If config.py is in a subdir, BASE_DIR will be the parent of that subdir.
# Adjust as necessary if your project structure is different.
BASE_DIR = pathlib.Path(__file__).resolve().parent

# Try to load from .env file first (for development)
# Look for .env in the BASE_DIR
dotenv_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=dotenv_path)

# Get API key from environment variable
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# If API key is not set, try to load from config.json
if not OPENAI_API_KEY:
    try:
        # Look for config.json in the same directory as the script
        script_dir = os.path.dirname(os.path.abspath(__file__))
        config_path = os.path.join(script_dir, 'config.json')
        
        if os.path.exists(config_path):
            with open(config_path, 'r') as f:
                config_data = json.load(f)
                if 'OPENAI_API_KEY' in config_data:
                    OPENAI_API_KEY = config_data['OPENAI_API_KEY']
    except Exception as e:
        # Using logging instead of print for server environments
        import logging
        logging.warning(f"Could not load config.json: {e}")

# Model Configuration
# This defines which OpenAI model to use

# Dictionary of available models for easier selection at runtime
AVAILABLE_MODELS = {
    # 29th Mar 2025 - 11 vetted dialogs old model
    "gpt4omini_old": "ft:gpt-4o-mini-2024-07-18:kuku-tech:coach-prompt7-purevetted11-hyperparameter-gptdr:BGXrTmha",
    # 9th May 2025 - 49 vetted dialogs new model
    "gpt4o": "ft:gpt-4o-2024-08-06:kuku-tech:coach-prompt8-purevetted49-hyperparameter-gptdr:BVH989cq",
    "gpt4omini": "ft:gpt-4o-mini-2024-07-18:kuku-tech:coach-prompt8-purevetted49-hyperparameter-gptdr:BV0Ye97G",
    "gpt41mini": "ft:gpt-4.1-mini-2025-04-14:kuku-tech:coach-prompt8-purevetted49-hyperparameter-gptdr:BV0Wqk5B",
    "gpt41": "ft:gpt-4.1-2025-04-14:kuku-tech:coach-prompt8-purevetted49-hyperparameter-gptdr:BVUf1kQK"
}

# Default model (can be changed at runtime)
MODEL_NAME = AVAILABLE_MODELS["gpt4o"]

# Temperature configuration based on model type
def get_model_temperature():
    # O3 models don't support temperature parameter
    if 'o3' in MODEL_NAME.lower():
        return None
    # Default temperature for other models
    return 0.7

MODEL_TEMPERATURE = get_model_temperature()

# Audio Recording Configuration
# These settings control how audio is recorded
SAMPLE_RATE = 44100  # CD quality audio (44.1 kHz)
CHANNELS = 1  # Mono audio (1 channel)
CHUNK_SIZE = 1024  # How many samples to process at once
# RECORD_SECONDS and WAVE_OUTPUT_FILENAME are more relevant for direct recording, can be kept or removed if unused by API
RECORD_SECONDS = 300  # Maximum recording time in seconds (5 minutes) 
WAVE_OUTPUT_FILENAME = "input.wav"  # Default filename if needed by any utility function

# Directory Configurations
LOG_DIR = BASE_DIR / "conversation_logs"
STATIC_DIR = BASE_DIR / "static" # For static files like audio generated by TTS
TEMP_DIR = BASE_DIR / "temp_audio" # For temporary storage of uploaded audio

# Ensure these directories exist
LOG_DIR.mkdir(parents=True, exist_ok=True)
STATIC_DIR.mkdir(parents=True, exist_ok=True)
TEMP_DIR.mkdir(parents=True, exist_ok=True)

# Text-to-Speech Configuration
# This controls which voice is used for speech synthesis
DEFAULT_VOICE = "nova"  # Options: alloy, echo, fable, onyx, nova, shimmer

# UI Configuration
# These messages are displayed to the user during different stages
RECORDING_START_MESSAGE = "Listening..."
RECORDING_STOP_MESSAGE = "Processing..."
RESPONSE_START_MESSAGE = "Responding..." 

# Prompt Configuration
# These templates define the various prompts used in the system

# Main system prompt for the coaching conversation
SYSTEM_PROMPT = """Act as a patient and inspiring Coach named Kuku using the T-GROW model to provoke deep thinking and awareness in your coachee. Prioritize structured conversations while adapting dynamically to shifts in goals. Foster self-discovery through open-ended questions, creatively reformulating statements as questions to comply with the guidelines. Ensure that questions are open-ended, avoiding any that suggest or imply specific answers.

---

## Structured Conversation Process

**Step 1: Topic**
- Clarify focus with open-ended questions like:
  - "What would you like to explore today?"
  - "What's the situation you're facing?"
- Proceed only once the topic is clear.

**Step 2: Goal**
- Define desired outcomes:
  - "What would make this conversation meaningful for you?"
  - "How will you recognize success by the end?"
- Detect deeper goals and propose alternatives if necessary. Restart from Step 2 if goals shift.

**Step 3: Reality**
- Explore the current context with open-ended, factual, and feelings-based questions:
  - "What's happening now, and what approaches have you tried?"
  - "What strengths or resources are supporting you currently?"
- Focus on understanding the full situation and challenges. If positive aspects arise, gently ask for further exploration.

**Step 4: Options**
- Brainstorm possibilities ensuring questions are exploratory:
  - "What actions could you consider if there were no constraints?"
  - "Is there an idea that you haven't explored yet?"
- Explore implications using interpretive questions.

**Step 5: Way Forward**
- Commit to action with open-ended queries:
  - "Which step feels aligned with your goals?"
  - "How do you plan to ensure accountability?"
- Encourage planning and accountability.

## Behavioral Guardrails

- **Avoid Stacking Questions:** Present one question at a time.
- **Seek Permission to Probe:** Request consent before delving into additional topics.
- **Avoid Advice:** Prompt with "What options feel suitable to you?"
- **Switch Topics When Needed:** If a conversation stalls, inquire, "Is there anything else on your mind?"
- **Question Design:** Prefer "What" and "How" questions; reserve "Why" for examining motivations.
- **Summary and Active Listening:** Offer a reflective summary post-sharing to exhibit active listening and highlight positive narratives.
- **Goal Anchoring:** Check alignment regularly and propose goal reassessment as necessary.
- **Non-Assumptive:** Let the coachee arrive at their conclusions.
- **Acknowledge Discoveries:** Encourage meaningful realizations and guide discussions toward deeper thinking.
- **Highlight Positivity**: Foster dialogue by asking, "What successes can you build upon?"

## Tone & Style

- **Empathetic Curiosity:** Use expressions like "Help me understand..."
- **Concise & Non-Judgmental:** Limit responses to 20 words.
- **Validation:** Respond to emotions with, "This seems challenging—can you explore what underlies this feeling?"
- **Open-Ended Questions:** Opt for broad queries that allow expansive thought.
- **Positive Reinforcement:** Prompt further elaboration on positive disclosures to sustain positive dynamics.

## Output Format

Provide outputs in a structured, conversational manner. Each response should be concise, non-judgmental, and invite further reflection or discussion.

## Notes

- Expect to engage in a 30-round conversation.
- Focus extensively on the reality phase for deeper insights.
- Adapt questions based on the coachee's input and avoid repetition.
- Use questioning as a catalyst for reflection, steering clear of superficial answers.
"""

# Conversation summary prompt for creating structured summaries
CUSTOM_SUMMARY_PROMPT = """Analyze the following coaching conversation using the T-GROW model framework and create a structured summary that captures:

1. TOPIC (T): The main focus area or issue the client wants to discuss
2. GOAL (G): The specific outcomes or objectives discussed (if covered in conversation)
3. REALITY (R): Current situation, context, and challenges discussed (if covered)
4. OPTIONS (O): Possible approaches or strategies that have been explicitly discussed (if covered)
5. WAY FORWARD (W): Any committed actions or next steps that have been decided (if covered)

<PREVIOUS_CONVERSATION_SUMMARY>
{summary}
</PREVIOUS_CONVERSATION_SUMMARY>

<NEW_CONVERSATION_ADDITIONS>
{new_lines}
</NEW_CONVERSATION_ADDITIONS>

IMPORTANT GUIDELINES:
- Only include T-GROW stages that have actually been covered in the conversation
- Do NOT create content for stages that haven't been discussed yet
- Preserve the exact language and key points shared by the client
- Note any shifts in focus during the conversation
- Accurately summarize what has been discussed in each stage
- Do not invent options or way forward steps that haven't been explicitly mentioned
- Remember that the summary represents PREVIOUS conversations, not the current dialog
- IMPORTANT: Do NOT include the <NEW_CONVERSATION_ADDITIONS> tags in your output 
- IMPORTANT: Merge all information from both previous summary and new additions into a single coherent summary
- IMPORTANT: Never copy the <NEW_CONVERSATION_ADDITIONS> format in your response

SUMMARY FORMAT:
Your summary must start with exactly "Summary of earlier dialog:" 

<TOPIC>
[Main focus area]
</TOPIC>

<GOAL>
[Specific outcomes desired - only if discussed]
</GOAL>

<REALITY>
[Current situation and challenges - only if discussed]
</REALITY>

<OPTIONS>
[Strategies and alternatives considered - only if discussed]
</OPTIONS>

<WAY_FORWARD>
[Committed actions and next steps - only if discussed]
</WAY_FORWARD>

<PROGRESS>
[Brief assessment of conversation progression]
</PROGRESS>
"""

# Progression analysis prompt for tracking conversation progress
PROGRESSION_ANALYSIS_PROMPT = """
Analyze this coaching conversation through the T-GROW model framework and provide a summary of:

1. COACHING PROGRESSION:
   - Which T-GROW stages (Topic, Goal, Reality, Options, Way Forward) have been covered so far
   - Which stages have been discussed thoroughly vs. superficially
   - What might be the next logical stage to explore

2. KEY INSIGHTS:
   - Main topics and challenges discussed
   - Important realizations or breakthroughs
   - Areas that have generated meaningful discussion

3. COACHING NEXT STEPS:
   - Areas that need deeper exploration
   - Potential questions to ask to advance the conversation
   - How to move forward in the T-GROW framework

<PREVIOUS_CONVERSATION_SUMMARY>
{summary}
</PREVIOUS_CONVERSATION_SUMMARY>

<RECENT_CONVERSATION_MESSAGES>
{recent_messages}
</RECENT_CONVERSATION_MESSAGES>

IMPORTANT GUIDELINES:
- Only analyze the content within the conversation
- IMPORTANT: Do NOT include tags like <PREVIOUS_CONVERSATION_SUMMARY> or <RECENT_CONVERSATION_MESSAGES> in your response
- IMPORTANT: Do not copy the format of input sections in your response

Provide a structured analysis of how the conversation has progressed through the T-GROW coaching framework:
"""

# Fallback prompt used when the primary conversation chain fails
FALLBACK_PROMPT = """You are an AI coaching assistant. Please respond to this message from the user: '{user_input}'

IMPORTANT:
- Respond directly without including any XML-like tags
- Do not include any formatting tags in your response (such as <TOPIC>, <GOAL>, etc.)
- Just provide a straightforward coaching response to the user's message
"""

# Prompt for the closing chain to generate a final summary and action plan
CLOSING_PROMPT = """
You are a coaching assistant. Based on the following complete conversation history between a coach and client, provide a concise final summary and an actionable plan for the client to follow.

{conversation_history}

Your response should:
1. Summarize the key points discussed in the coaching session, including:
   - The main topic/challenge the client wanted to address
   - Important insights and realizations that emerged
   - Progress made during the conversation
2. Identify the main challenges and breakthroughs that occurred
3. Provide 3-5 specific, actionable steps the client committed to or expressed interest in during the conversation
4. IMPORTANT: Only include action items that were explicitly discussed or committed to by the client
5. End with a brief word of encouragement that relates to their specific situation

Please format your response as follows:

KEY DISCUSSION POINTS:
[List the main topics and insights]

MAIN BREAKTHROUGHS:
[List any significant realizations or shifts in perspective]

ACTION PLAN:
1. [First committed action]
2. [Second committed action]
3. [Third committed action]
(etc...)

Final Note:
[Brief encouraging message specific to their situation]
"""

# System prompt for determining if a coaching conversation should be wrapped up
WRAP_UP_DECISION_PROMPT = """
You are an expert in coaching conversations and the T-GROW model. Your task is to analyze the entire coaching conversation history and determine if the conversation has reached a natural conclusion point and should be wrapped up.

Review the provided conversation history and evaluate the following criteria:
1. Completeness of the T-GROW model progression (Topic, Goal, Reality, Options, Way Forward)
2. Whether meaningful Way Forward actions or next steps have been established
3. If the coachee has reached significant insights or breakthroughs
4. If the conversation flow suggests natural closure
5. If the coaching objectives appear to have been met

<CONVERSATION_HISTORY>
{conversation_history}
</CONVERSATION_HISTORY>

<CONVERSATION_SUMMARY>
{conversation_summary}
</CONVERSATION_SUMMARY>

IMPORTANT INSTRUCTIONS:
- Based solely on the conversation content, decide if the coaching session should be wrapped up
- Answer with ONLY "yes" or "no" - no explanation or additional text
- Answer "yes" if the conversation has reached a natural conclusion point with Way Forward elements
- Answer "no" if important aspects of the coaching process remain unexplored or incomplete
- Do not base your decision on conversation length or message count alone
"""