services:
  - type: web
    name: kuku-coach-api
    env: python
    plan: starter  # IMPORTANT: The 'starter' plan is for development and testing. Upgrade to 'starter+' or a standard plan for production workloads.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: kuku-coach-api
          property: port
    # Add your environment variables here
    # - key: OPENAI_API_KEY
    #   sync: false  # This will prompt you to enter the value securely 