services:
  - type: web
    name: kuku-coach-api
    env: python
    plan: starter  # Free tier - upgrade to starter+ for production
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: kuku-coach-api
          property: port
    # Add your environment variables here
    # - key: OPENAI_API_KEY
    #   sync: false  # This will prompt you to enter the value securely 